service: integrations-functions-poc

frameworkVersion: '3'

custom:
  localstack:
    stages:
      - local

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 256

functions:
  sampleFunction:
    handler: src/handlers/sampleFunction.handler

plugins:
  - serverless-localstack

